# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bug_fix',
            new_name='Bug',
        ),
    ]
