# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-02 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracker', '0003_auto_20190328_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('suggestion_content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=1)),
                ('upvotes', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('a', 'Backlog'), ('b', 'In Progress'), ('c', 'Completed')], default='a', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Backlog'), ('b', 'In Progress'), ('c', 'Completed')], default='a', max_length=20),
        ),
    ]
