# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_bugcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_comments', to='issue_tracker.Bug'),
        ),
    ]
